# Configuration for the file server application
serve_folder: serveFolder
temp_dir: temp_zips
upload_folder: serveFolder
allowed_extensions:
  - .txt
  - .pdf
  - .jpg
  - .jpeg
  - .png
  - .zip
  - .csv
  - .json
  - .md
max_content_length: 5368709120  # 5GB in bytes