# Configuration for the file server application
serve_folder: data
temp_dir: temp
upload_folder: data
allowed_extensions:
  - .txt
  - .pdf
  - .jpg
  - .jpeg
  - .png
  - .zip
  - .csv
  - .json
  - .md
max_content_length: 5368709120  # 5GB in bytes
use_pure_flask: false # Set to true for pure Flask serving (no Nginx); false for Nginx mode, both are possible